/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mapler.nexmo;
 
import com.mapler.sendhub.SendHubLoginUI;
import com.mapler.utility.HttpHelper;
import com.mapler.utility.IConstant;
import com.mapler.utility.Util;
import java.awt.Color;
import java.net.URL;
import javax.swing.JFrame;
import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;
import org.dom4j.Document;
import org.dom4j.DocumentHelper;

/**
 *
 * @author JAYED
 */
public class NexmoLoginUI extends javax.swing.JDialog {

    /**
     * Creates new form NexmoLoginUI
     */
    private static Logger log = Logger.getLogger(SendHubLoginUI.class);
    DBUtil dBUtil=new DBUtil();
    public NexmoLoginUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        PropertyConfigurator.configure("./src/log4j.properties");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jBKill = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Nexmo");

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBKill.setText("Stop Process");
        jBKill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKillActionPerformed(evt);
            }
        });

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBKill)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(106, 106, 106))))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(2, 2, 2)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBKill)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
            this.message.setText("");
            String name = this.username.getText();
            String pass = this.password.getText();
            if ((name == null || name.isEmpty()) && (pass == null || pass.isEmpty())) {
                this.message.setText("User name and password can not be empty");
                return;
            } else if (name == null || name.isEmpty()) {
                this.message.setText("User name can not be empty");
                return;
            } else if (pass == null || pass.isEmpty()) {
                this.message.setText("Password can not be empty");
                return;
            }
            // mysql select code
            UserInfo userInfo=dBUtil.getUserInfoFromDb(name, pass);
            if (userInfo!=null) {
                String userid = "jayed";//userInfo.getId();
                String usertype = "jayed";//userInfo.getType();               
                NexmoMainUI mainUI = new NexmoMainUI(name, pass, usertype, userid);
                mainUI.setVisible(true);
                mainUI.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                mainUI.setAlwaysOnTop(false);

                this.dispose();
            } else {
                this.message.setText("Error on request. Please contact with system administrator.");
                this.message.setBackground(Color.red);
            }
        } catch (Throwable ex) {
            this.message.setText("Error " + ex.getMessage());
            this.message.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed
     private boolean isOKToLogin(String mac) {
        try {
            if (!Util.isLoginByMac(mac)) {
                return true;
            }

            int p = Util.isAppsRunning();
            if (p == 0) {
                this.message.setText("Unable to execute iRobot. Please contact with system administrator.");
                this.jButton1.setVisible(false);
                this.jBKill.setVisible(false);
                return true;
            } else if (p == 1 || p == 2) {
                String uri = "http://" + IConstant.HOSTNAME + "/index.php?r=userAccount/logoutByMac&mac=" + mac;
                String response = HttpHelper.post(new URL(uri), "");

                Document document = DocumentHelper.parseText(response);
                String errorCode = document.valueOf("Response/errorcode");
                if (!errorCode.equalsIgnoreCase("001")) {
                    this.message.setText("Error on apps running. Please contact with system administrator.");
                    this.jButton1.setVisible(false);
                    this.jBKill.setVisible(false);
                } else {
                    return true;
                }

            } else if (p > 1) {
                this.message.setText("Too many java / iRobot process running. Kill first then start again.");
                this.jButton1.setVisible(false);
                this.jBKill.setVisible(true);
            }
        } catch (Throwable ex) {
            ex.printStackTrace();
            log.error("doInit: " + ex.getMessage());
        }
        return false;
    }
    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jBKillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKillActionPerformed
        try {
            Runtime.getRuntime().exec("taskkill /F /IM java.exe");
            Runtime.getRuntime().exec("taskkill /F /IM iRobot.exe");
            Runtime.getRuntime().exec("taskkill /F /IM javaw.exe");
        } catch (Throwable ex) {
            ex.printStackTrace();
            log.error("jBKillActionPerformed: " + ex.getMessage());
        }
    }//GEN-LAST:event_jBKillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NexmoLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NexmoLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NexmoLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NexmoLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NexmoLoginUI dialog = new NexmoLoginUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBKill;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel message;
    private javax.swing.JTextField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
